begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to Elasticsearch under one or more contributor  * license agreements. See the NOTICE file distributed with  * this work for additional information regarding copyright  * ownership. Elasticsearch licenses this file to you under  * the Apache License, Version 2.0 (the "License"); you may  * not use this file except in compliance with the License.  * You may obtain a copy of the License at  *  *    http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied.  See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
DECL|package|org.elasticsearch.monitor.os
package|package
name|org
operator|.
name|elasticsearch
operator|.
name|monitor
operator|.
name|os
package|;
end_package

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|common
operator|.
name|component
operator|.
name|AbstractComponent
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|common
operator|.
name|settings
operator|.
name|Setting
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|common
operator|.
name|settings
operator|.
name|Setting
operator|.
name|Property
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|common
operator|.
name|settings
operator|.
name|Settings
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|common
operator|.
name|unit
operator|.
name|TimeValue
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|common
operator|.
name|util
operator|.
name|SingleObjectCache
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|common
operator|.
name|util
operator|.
name|concurrent
operator|.
name|EsExecutors
import|;
end_import

begin_comment
comment|/**  *  */
end_comment

begin_class
DECL|class|OsService
specifier|public
class|class
name|OsService
extends|extends
name|AbstractComponent
block|{
DECL|field|probe
specifier|private
specifier|final
name|OsProbe
name|probe
decl_stmt|;
DECL|field|info
specifier|private
specifier|final
name|OsInfo
name|info
decl_stmt|;
DECL|field|osStatsCache
specifier|private
name|SingleObjectCache
argument_list|<
name|OsStats
argument_list|>
name|osStatsCache
decl_stmt|;
DECL|field|REFRESH_INTERVAL_SETTING
specifier|public
specifier|static
specifier|final
name|Setting
argument_list|<
name|TimeValue
argument_list|>
name|REFRESH_INTERVAL_SETTING
init|=
name|Setting
operator|.
name|timeSetting
argument_list|(
literal|"monitor.os.refresh_interval"
argument_list|,
name|TimeValue
operator|.
name|timeValueSeconds
argument_list|(
literal|1
argument_list|)
argument_list|,
name|TimeValue
operator|.
name|timeValueSeconds
argument_list|(
literal|1
argument_list|)
argument_list|,
name|Property
operator|.
name|NodeScope
argument_list|)
decl_stmt|;
DECL|method|OsService
specifier|public
name|OsService
parameter_list|(
name|Settings
name|settings
parameter_list|)
block|{
name|super
argument_list|(
name|settings
argument_list|)
expr_stmt|;
name|this
operator|.
name|probe
operator|=
name|OsProbe
operator|.
name|getInstance
argument_list|()
expr_stmt|;
name|TimeValue
name|refreshInterval
init|=
name|REFRESH_INTERVAL_SETTING
operator|.
name|get
argument_list|(
name|settings
argument_list|)
decl_stmt|;
name|this
operator|.
name|info
operator|=
name|probe
operator|.
name|osInfo
argument_list|()
expr_stmt|;
name|this
operator|.
name|info
operator|.
name|refreshInterval
operator|=
name|refreshInterval
operator|.
name|millis
argument_list|()
expr_stmt|;
name|this
operator|.
name|info
operator|.
name|allocatedProcessors
operator|=
name|EsExecutors
operator|.
name|boundedNumberOfProcessors
argument_list|(
name|settings
argument_list|)
expr_stmt|;
name|osStatsCache
operator|=
operator|new
name|OsStatsCache
argument_list|(
name|refreshInterval
argument_list|,
name|probe
operator|.
name|osStats
argument_list|()
argument_list|)
expr_stmt|;
name|logger
operator|.
name|debug
argument_list|(
literal|"using refresh_interval [{}]"
argument_list|,
name|refreshInterval
argument_list|)
expr_stmt|;
block|}
DECL|method|info
specifier|public
name|OsInfo
name|info
parameter_list|()
block|{
return|return
name|this
operator|.
name|info
return|;
block|}
DECL|method|stats
specifier|public
specifier|synchronized
name|OsStats
name|stats
parameter_list|()
block|{
return|return
name|osStatsCache
operator|.
name|getOrRefresh
argument_list|()
return|;
block|}
DECL|class|OsStatsCache
specifier|private
class|class
name|OsStatsCache
extends|extends
name|SingleObjectCache
argument_list|<
name|OsStats
argument_list|>
block|{
DECL|method|OsStatsCache
specifier|public
name|OsStatsCache
parameter_list|(
name|TimeValue
name|interval
parameter_list|,
name|OsStats
name|initValue
parameter_list|)
block|{
name|super
argument_list|(
name|interval
argument_list|,
name|initValue
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
DECL|method|refresh
specifier|protected
name|OsStats
name|refresh
parameter_list|()
block|{
return|return
name|probe
operator|.
name|osStats
argument_list|()
return|;
block|}
block|}
block|}
end_class

end_unit

