begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to Elasticsearch under one or more contributor  * license agreements. See the NOTICE file distributed with  * this work for additional information regarding copyright  * ownership. Elasticsearch licenses this file to you under  * the Apache License, Version 2.0 (the "License"); you may  * not use this file except in compliance with the License.  * You may obtain a copy of the License at  *  *    http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied.  See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
DECL|package|org.elasticsearch.index
package|package
name|org
operator|.
name|elasticsearch
operator|.
name|index
package|;
end_package

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|cluster
operator|.
name|ClusterState
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|common
operator|.
name|Strings
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|test
operator|.
name|ESTestCase
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|lucene
operator|.
name|util
operator|.
name|TestUtil
operator|.
name|randomSimpleString
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|hamcrest
operator|.
name|Matchers
operator|.
name|containsString
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|hamcrest
operator|.
name|Matchers
operator|.
name|not
import|;
end_import

begin_class
DECL|class|IndexTests
specifier|public
class|class
name|IndexTests
extends|extends
name|ESTestCase
block|{
DECL|method|testToString
specifier|public
name|void
name|testToString
parameter_list|()
block|{
name|assertEquals
argument_list|(
literal|"[name/uuid]"
argument_list|,
operator|new
name|Index
argument_list|(
literal|"name"
argument_list|,
literal|"uuid"
argument_list|)
operator|.
name|toString
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"[name]"
argument_list|,
operator|new
name|Index
argument_list|(
literal|"name"
argument_list|,
name|ClusterState
operator|.
name|UNKNOWN_UUID
argument_list|)
operator|.
name|toString
argument_list|()
argument_list|)
expr_stmt|;
name|Index
name|random
init|=
operator|new
name|Index
argument_list|(
name|randomSimpleString
argument_list|(
name|random
argument_list|()
argument_list|,
literal|1
argument_list|,
literal|100
argument_list|)
argument_list|,
name|usually
argument_list|()
condition|?
name|Strings
operator|.
name|randomBase64UUID
argument_list|(
name|random
argument_list|()
argument_list|)
else|:
name|ClusterState
operator|.
name|UNKNOWN_UUID
argument_list|)
decl_stmt|;
name|assertThat
argument_list|(
name|random
operator|.
name|toString
argument_list|()
argument_list|,
name|containsString
argument_list|(
name|random
operator|.
name|getName
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|ClusterState
operator|.
name|UNKNOWN_UUID
operator|.
name|equals
argument_list|(
name|random
operator|.
name|getUUID
argument_list|()
argument_list|)
condition|)
block|{
name|assertThat
argument_list|(
name|random
operator|.
name|toString
argument_list|()
argument_list|,
name|not
argument_list|(
name|containsString
argument_list|(
name|random
operator|.
name|getUUID
argument_list|()
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|assertThat
argument_list|(
name|random
operator|.
name|toString
argument_list|()
argument_list|,
name|containsString
argument_list|(
name|random
operator|.
name|getUUID
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
block|}
block|}
block|}
end_class

end_unit

