begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to Elasticsearch under one or more contributor  * license agreements. See the NOTICE file distributed with  * this work for additional information regarding copyright  * ownership. Elasticsearch licenses this file to you under  * the Apache License, Version 2.0 (the "License"); you may  * not use this file except in compliance with the License.  * You may obtain a copy of the License at  *  *    http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied.  See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
DECL|package|org.elasticsearch.index.analysis
package|package
name|org
operator|.
name|elasticsearch
operator|.
name|index
operator|.
name|analysis
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|lucene
operator|.
name|analysis
operator|.
name|TokenStream
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|lucene
operator|.
name|analysis
operator|.
name|core
operator|.
name|TypeTokenFilter
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|common
operator|.
name|settings
operator|.
name|Settings
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|env
operator|.
name|Environment
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|index
operator|.
name|IndexSettings
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Arrays
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|HashSet
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Set
import|;
end_import

begin_comment
comment|/**  * A {@link TokenFilterFactory} for {@link TypeTokenFilter}. This filter only  * keep tokens that are contained in the set configured via  * {@value #KEEP_TYPES_KEY} setting.  *<p>  * Configuration options:  *<ul>  *<li>{@value #KEEP_TYPES_KEY} the array of words / tokens to keep.</li>  *</ul>  */
end_comment

begin_class
DECL|class|KeepTypesFilterFactory
specifier|public
class|class
name|KeepTypesFilterFactory
extends|extends
name|AbstractTokenFilterFactory
block|{
DECL|field|keepTypes
specifier|private
specifier|final
name|Set
argument_list|<
name|String
argument_list|>
name|keepTypes
decl_stmt|;
DECL|field|KEEP_TYPES_KEY
specifier|private
specifier|static
specifier|final
name|String
name|KEEP_TYPES_KEY
init|=
literal|"types"
decl_stmt|;
DECL|method|KeepTypesFilterFactory
specifier|public
name|KeepTypesFilterFactory
parameter_list|(
name|IndexSettings
name|indexSettings
parameter_list|,
name|Environment
name|env
parameter_list|,
name|String
name|name
parameter_list|,
name|Settings
name|settings
parameter_list|)
block|{
name|super
argument_list|(
name|indexSettings
argument_list|,
name|name
argument_list|,
name|settings
argument_list|)
expr_stmt|;
specifier|final
name|String
index|[]
name|arrayKeepTypes
init|=
name|settings
operator|.
name|getAsArray
argument_list|(
name|KEEP_TYPES_KEY
argument_list|,
literal|null
argument_list|)
decl_stmt|;
if|if
condition|(
operator|(
name|arrayKeepTypes
operator|==
literal|null
operator|)
condition|)
block|{
throw|throw
operator|new
name|IllegalArgumentException
argument_list|(
literal|"keep_types requires `"
operator|+
name|KEEP_TYPES_KEY
operator|+
literal|"` to be configured"
argument_list|)
throw|;
block|}
name|this
operator|.
name|keepTypes
operator|=
operator|new
name|HashSet
argument_list|<>
argument_list|(
name|Arrays
operator|.
name|asList
argument_list|(
name|arrayKeepTypes
argument_list|)
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
DECL|method|create
specifier|public
name|TokenStream
name|create
parameter_list|(
name|TokenStream
name|tokenStream
parameter_list|)
block|{
return|return
operator|new
name|TypeTokenFilter
argument_list|(
name|tokenStream
argument_list|,
name|keepTypes
argument_list|,
literal|true
argument_list|)
return|;
block|}
block|}
end_class

end_unit

