begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to Elasticsearch under one or more contributor  * license agreements. See the NOTICE file distributed with  * this work for additional information regarding copyright  * ownership. Elasticsearch licenses this file to you under  * the Apache License, Version 2.0 (the "License"); you may  * not use this file except in compliance with the License.  * You may obtain a copy of the License at  *  *    http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied.  See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
DECL|package|org.elasticsearch.search.rescore
package|package
name|org
operator|.
name|elasticsearch
operator|.
name|search
operator|.
name|rescore
package|;
end_package

begin_class
DECL|class|RescoreSearchContext
specifier|public
class|class
name|RescoreSearchContext
block|{
DECL|field|windowSize
specifier|private
name|int
name|windowSize
decl_stmt|;
DECL|field|type
specifier|private
specifier|final
name|String
name|type
decl_stmt|;
DECL|field|rescorer
specifier|private
specifier|final
name|Rescorer
name|rescorer
decl_stmt|;
DECL|method|RescoreSearchContext
specifier|public
name|RescoreSearchContext
parameter_list|(
name|String
name|type
parameter_list|,
name|int
name|windowSize
parameter_list|,
name|Rescorer
name|rescorer
parameter_list|)
block|{
name|super
argument_list|()
expr_stmt|;
name|this
operator|.
name|type
operator|=
name|type
expr_stmt|;
name|this
operator|.
name|windowSize
operator|=
name|windowSize
expr_stmt|;
name|this
operator|.
name|rescorer
operator|=
name|rescorer
expr_stmt|;
block|}
DECL|method|rescorer
specifier|public
name|Rescorer
name|rescorer
parameter_list|()
block|{
return|return
name|rescorer
return|;
block|}
DECL|method|getType
specifier|public
name|String
name|getType
parameter_list|()
block|{
return|return
name|type
return|;
block|}
DECL|method|setWindowSize
specifier|public
name|void
name|setWindowSize
parameter_list|(
name|int
name|windowSize
parameter_list|)
block|{
name|this
operator|.
name|windowSize
operator|=
name|windowSize
expr_stmt|;
block|}
DECL|method|window
specifier|public
name|int
name|window
parameter_list|()
block|{
return|return
name|windowSize
return|;
block|}
block|}
end_class

end_unit

