begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to Elastic Search and Shay Banon under one  * or more contributor license agreements.  See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership. Elastic Search licenses this  * file to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License.  You may obtain a copy of the License at  *  *    http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied.  See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
DECL|package|org.elasticsearch.index.merge.scheduler
package|package
name|org
operator|.
name|elasticsearch
operator|.
name|index
operator|.
name|merge
operator|.
name|scheduler
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|lucene
operator|.
name|index
operator|.
name|ConcurrentMergeScheduler
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|lucene
operator|.
name|index
operator|.
name|IndexWriter
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|lucene
operator|.
name|index
operator|.
name|MergePolicy
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|lucene
operator|.
name|index
operator|.
name|MergeScheduler
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|common
operator|.
name|inject
operator|.
name|Inject
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|common
operator|.
name|settings
operator|.
name|Settings
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|index
operator|.
name|settings
operator|.
name|IndexSettings
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|index
operator|.
name|shard
operator|.
name|AbstractIndexShardComponent
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|index
operator|.
name|shard
operator|.
name|ShardId
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_comment
comment|/**  * @author kimchy (shay.banon)  */
end_comment

begin_class
DECL|class|ConcurrentMergeSchedulerProvider
specifier|public
class|class
name|ConcurrentMergeSchedulerProvider
extends|extends
name|AbstractIndexShardComponent
implements|implements
name|MergeSchedulerProvider
block|{
DECL|field|maxThreadCount
specifier|private
specifier|final
name|int
name|maxThreadCount
decl_stmt|;
DECL|method|ConcurrentMergeSchedulerProvider
annotation|@
name|Inject
specifier|public
name|ConcurrentMergeSchedulerProvider
parameter_list|(
name|ShardId
name|shardId
parameter_list|,
annotation|@
name|IndexSettings
name|Settings
name|indexSettings
parameter_list|)
block|{
name|super
argument_list|(
name|shardId
argument_list|,
name|indexSettings
argument_list|)
expr_stmt|;
comment|// TODO LUCENE MONITOR this will change in Lucene 4.0
name|this
operator|.
name|maxThreadCount
operator|=
name|componentSettings
operator|.
name|getAsInt
argument_list|(
literal|"max_thread_count"
argument_list|,
name|Math
operator|.
name|max
argument_list|(
literal|1
argument_list|,
name|Math
operator|.
name|min
argument_list|(
literal|3
argument_list|,
name|Runtime
operator|.
name|getRuntime
argument_list|()
operator|.
name|availableProcessors
argument_list|()
operator|/
literal|2
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
name|logger
operator|.
name|debug
argument_list|(
literal|"using [concurrent] merge scheduler with max_thread_count[{}]"
argument_list|,
name|maxThreadCount
argument_list|)
expr_stmt|;
block|}
DECL|method|newMergeScheduler
annotation|@
name|Override
specifier|public
name|MergeScheduler
name|newMergeScheduler
parameter_list|()
block|{
name|ConcurrentMergeScheduler
name|concurrentMergeScheduler
init|=
operator|new
name|CustomConcurrentMergeScheduler
argument_list|()
decl_stmt|;
name|concurrentMergeScheduler
operator|.
name|setMaxThreadCount
argument_list|(
name|maxThreadCount
argument_list|)
expr_stmt|;
return|return
name|concurrentMergeScheduler
return|;
block|}
DECL|class|CustomConcurrentMergeScheduler
specifier|private
class|class
name|CustomConcurrentMergeScheduler
extends|extends
name|ConcurrentMergeScheduler
block|{
DECL|method|getMergeThread
annotation|@
name|Override
specifier|protected
name|MergeThread
name|getMergeThread
parameter_list|(
name|IndexWriter
name|writer
parameter_list|,
name|MergePolicy
operator|.
name|OneMerge
name|merge
parameter_list|)
throws|throws
name|IOException
block|{
name|MergeThread
name|thread
init|=
name|super
operator|.
name|getMergeThread
argument_list|(
name|writer
argument_list|,
name|merge
argument_list|)
decl_stmt|;
name|thread
operator|.
name|setName
argument_list|(
literal|"["
operator|+
name|shardId
operator|.
name|index
argument_list|()
operator|.
name|name
argument_list|()
operator|+
literal|"]["
operator|+
name|shardId
operator|.
name|id
argument_list|()
operator|+
literal|"]: "
operator|+
name|thread
operator|.
name|getName
argument_list|()
argument_list|)
expr_stmt|;
return|return
name|thread
return|;
block|}
block|}
block|}
end_class

end_unit

