begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to Elasticsearch under one or more contributor  * license agreements. See the NOTICE file distributed with  * this work for additional information regarding copyright  * ownership. Elasticsearch licenses this file to you under  * the Apache License, Version 2.0 (the "License"); you may  * not use this file except in compliance with the License.  * You may obtain a copy of the License at  *  *    http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied.  See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
DECL|package|org.elasticsearch.rest.action
package|package
name|org
operator|.
name|elasticsearch
operator|.
name|rest
operator|.
name|action
package|;
end_package

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|common
operator|.
name|xcontent
operator|.
name|ToXContent
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|common
operator|.
name|xcontent
operator|.
name|XContentBuilder
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|rest
operator|.
name|BytesRestResponse
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|rest
operator|.
name|RestChannel
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|rest
operator|.
name|RestResponse
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|rest
operator|.
name|RestStatus
import|;
end_import

begin_comment
comment|/**  * A REST based action listener that assumes the response is of type {@link ToXContent} and automatically  * builds an XContent based response (wrapping the toXContent in startObject/endObject).  */
end_comment

begin_class
DECL|class|RestToXContentListener
specifier|public
class|class
name|RestToXContentListener
parameter_list|<
name|Response
extends|extends
name|ToXContent
parameter_list|>
extends|extends
name|RestResponseListener
argument_list|<
name|Response
argument_list|>
block|{
DECL|method|RestToXContentListener
specifier|public
name|RestToXContentListener
parameter_list|(
name|RestChannel
name|channel
parameter_list|)
block|{
name|super
argument_list|(
name|channel
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
DECL|method|buildResponse
specifier|public
specifier|final
name|RestResponse
name|buildResponse
parameter_list|(
name|Response
name|response
parameter_list|)
throws|throws
name|Exception
block|{
return|return
name|buildResponse
argument_list|(
name|response
argument_list|,
name|channel
operator|.
name|newBuilder
argument_list|()
argument_list|)
return|;
block|}
DECL|method|buildResponse
specifier|public
specifier|final
name|RestResponse
name|buildResponse
parameter_list|(
name|Response
name|response
parameter_list|,
name|XContentBuilder
name|builder
parameter_list|)
throws|throws
name|Exception
block|{
name|builder
operator|.
name|startObject
argument_list|()
expr_stmt|;
name|response
operator|.
name|toXContent
argument_list|(
name|builder
argument_list|,
name|channel
operator|.
name|request
argument_list|()
argument_list|)
expr_stmt|;
name|builder
operator|.
name|endObject
argument_list|()
expr_stmt|;
return|return
operator|new
name|BytesRestResponse
argument_list|(
name|getStatus
argument_list|(
name|response
argument_list|)
argument_list|,
name|builder
argument_list|)
return|;
block|}
DECL|method|getStatus
specifier|protected
name|RestStatus
name|getStatus
parameter_list|(
name|Response
name|response
parameter_list|)
block|{
return|return
name|RestStatus
operator|.
name|OK
return|;
block|}
block|}
end_class

end_unit

