begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to Elasticsearch under one or more contributor  * license agreements. See the NOTICE file distributed with  * this work for additional information regarding copyright  * ownership. Elasticsearch licenses this file to you under  * the Apache License, Version 2.0 (the "License"); you may  * not use this file except in compliance with the License.  * You may obtain a copy of the License at  *  *    http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied.  See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
DECL|package|org.elasticsearch.client
package|package
name|org
operator|.
name|elasticsearch
operator|.
name|client
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|http
operator|.
name|RequestLine
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|http
operator|.
name|StatusLine
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_class
DECL|class|ElasticsearchResponseException
specifier|public
class|class
name|ElasticsearchResponseException
extends|extends
name|IOException
block|{
DECL|field|node
specifier|private
specifier|final
name|Node
name|node
decl_stmt|;
DECL|field|requestLine
specifier|private
specifier|final
name|RequestLine
name|requestLine
decl_stmt|;
DECL|field|statusLine
specifier|private
specifier|final
name|StatusLine
name|statusLine
decl_stmt|;
DECL|method|ElasticsearchResponseException
name|ElasticsearchResponseException
parameter_list|(
name|RequestLine
name|requestLine
parameter_list|,
name|Node
name|node
parameter_list|,
name|StatusLine
name|statusLine
parameter_list|)
block|{
name|super
argument_list|(
name|buildMessage
argument_list|(
name|requestLine
argument_list|,
name|node
argument_list|,
name|statusLine
argument_list|)
argument_list|)
expr_stmt|;
name|this
operator|.
name|node
operator|=
name|node
expr_stmt|;
name|this
operator|.
name|requestLine
operator|=
name|requestLine
expr_stmt|;
name|this
operator|.
name|statusLine
operator|=
name|statusLine
expr_stmt|;
block|}
DECL|method|buildMessage
specifier|private
specifier|static
name|String
name|buildMessage
parameter_list|(
name|RequestLine
name|requestLine
parameter_list|,
name|Node
name|node
parameter_list|,
name|StatusLine
name|statusLine
parameter_list|)
block|{
return|return
name|requestLine
operator|.
name|getMethod
argument_list|()
operator|+
literal|" "
operator|+
name|node
operator|.
name|getHttpHost
argument_list|()
operator|+
name|requestLine
operator|.
name|getUri
argument_list|()
operator|+
literal|": "
operator|+
name|statusLine
operator|.
name|toString
argument_list|()
return|;
block|}
DECL|method|isRecoverable
specifier|public
name|boolean
name|isRecoverable
parameter_list|()
block|{
comment|//clients don't retry on 500 because elasticsearch still misuses it instead of 400 in some places
return|return
name|statusLine
operator|.
name|getStatusCode
argument_list|()
operator|>=
literal|502
operator|&&
name|statusLine
operator|.
name|getStatusCode
argument_list|()
operator|<=
literal|504
return|;
block|}
DECL|method|getNode
specifier|public
name|Node
name|getNode
parameter_list|()
block|{
return|return
name|node
return|;
block|}
DECL|method|getRequestLine
specifier|public
name|RequestLine
name|getRequestLine
parameter_list|()
block|{
return|return
name|requestLine
return|;
block|}
DECL|method|getStatusLine
specifier|public
name|StatusLine
name|getStatusLine
parameter_list|()
block|{
return|return
name|statusLine
return|;
block|}
block|}
end_class

end_unit

