begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to Elasticsearch under one or more contributor  * license agreements. See the NOTICE file distributed with  * this work for additional information regarding copyright  * ownership. Elasticsearch licenses this file to you under  * the Apache License, Version 2.0 (the "License"); you may  * not use this file except in compliance with the License.  * You may obtain a copy of the License at  *  *    http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied.  See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
DECL|package|org.elasticsearch.common.bytes
package|package
name|org
operator|.
name|elasticsearch
operator|.
name|common
operator|.
name|bytes
package|;
end_package

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|common
operator|.
name|io
operator|.
name|stream
operator|.
name|BytesStreamOutput
import|;
end_import

begin_import
import|import
name|org
operator|.
name|hamcrest
operator|.
name|Matchers
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_class
DECL|class|BytesArrayTests
specifier|public
class|class
name|BytesArrayTests
extends|extends
name|AbstractBytesReferenceTestCase
block|{
annotation|@
name|Override
DECL|method|newBytesReference
specifier|protected
name|BytesReference
name|newBytesReference
parameter_list|(
name|int
name|length
parameter_list|)
throws|throws
name|IOException
block|{
comment|// we know bytes stream output always creates a paged bytes reference, we use it to create randomized content
specifier|final
name|BytesStreamOutput
name|out
init|=
operator|new
name|BytesStreamOutput
argument_list|(
name|length
argument_list|)
decl_stmt|;
for|for
control|(
name|int
name|i
init|=
literal|0
init|;
name|i
operator|<
name|length
condition|;
name|i
operator|++
control|)
block|{
name|out
operator|.
name|writeByte
argument_list|(
operator|(
name|byte
operator|)
name|random
argument_list|()
operator|.
name|nextInt
argument_list|(
literal|1
operator|<<
literal|8
argument_list|)
argument_list|)
expr_stmt|;
block|}
name|assertEquals
argument_list|(
name|length
argument_list|,
name|out
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
name|BytesArray
name|ref
init|=
operator|new
name|BytesArray
argument_list|(
name|out
operator|.
name|bytes
argument_list|()
operator|.
name|toBytesRef
argument_list|()
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
name|length
argument_list|,
name|ref
operator|.
name|length
argument_list|()
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|ref
operator|instanceof
name|BytesArray
argument_list|)
expr_stmt|;
name|assertThat
argument_list|(
name|ref
operator|.
name|length
argument_list|()
argument_list|,
name|Matchers
operator|.
name|equalTo
argument_list|(
name|length
argument_list|)
argument_list|)
expr_stmt|;
return|return
name|ref
return|;
block|}
DECL|method|testArray
specifier|public
name|void
name|testArray
parameter_list|()
throws|throws
name|IOException
block|{
name|int
index|[]
name|sizes
init|=
block|{
literal|0
block|,
name|randomInt
argument_list|(
name|PAGE_SIZE
argument_list|)
block|,
name|PAGE_SIZE
block|,
name|randomIntBetween
argument_list|(
literal|2
argument_list|,
name|PAGE_SIZE
operator|*
name|randomIntBetween
argument_list|(
literal|2
argument_list|,
literal|5
argument_list|)
argument_list|)
block|}
decl_stmt|;
for|for
control|(
name|int
name|i
init|=
literal|0
init|;
name|i
operator|<
name|sizes
operator|.
name|length
condition|;
name|i
operator|++
control|)
block|{
name|BytesArray
name|pbr
init|=
operator|(
name|BytesArray
operator|)
name|newBytesReference
argument_list|(
name|sizes
index|[
name|i
index|]
argument_list|)
decl_stmt|;
name|byte
index|[]
name|array
init|=
name|pbr
operator|.
name|array
argument_list|()
decl_stmt|;
name|assertNotNull
argument_list|(
name|array
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
name|sizes
index|[
name|i
index|]
argument_list|,
name|array
operator|.
name|length
argument_list|)
expr_stmt|;
name|assertSame
argument_list|(
name|array
argument_list|,
name|pbr
operator|.
name|array
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
DECL|method|testArrayOffset
specifier|public
name|void
name|testArrayOffset
parameter_list|()
throws|throws
name|IOException
block|{
name|int
name|length
init|=
name|randomInt
argument_list|(
name|PAGE_SIZE
operator|*
name|randomIntBetween
argument_list|(
literal|2
argument_list|,
literal|5
argument_list|)
argument_list|)
decl_stmt|;
name|BytesArray
name|pbr
init|=
operator|(
name|BytesArray
operator|)
name|newBytesReference
argument_list|(
name|length
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
literal|0
argument_list|,
name|pbr
operator|.
name|offset
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

