begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Copyright 2010 Ning, Inc.  *  * Ning licenses this file to you under the Apache License, version 2.0  * (the "License"); you may not use this file except in compliance with the  * License.  You may obtain a copy of the License at:  *  *    http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT  * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the  * License for the specific language governing permissions and limitations  * under the License.  *  */
end_comment

begin_package
DECL|package|org.elasticsearch.util.http.client
package|package
name|org
operator|.
name|elasticsearch
operator|.
name|util
operator|.
name|http
operator|.
name|client
package|;
end_package

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|util
operator|.
name|logging
operator|.
name|ESLogger
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|util
operator|.
name|logging
operator|.
name|Loggers
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|ArrayList
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Collection
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Collections
import|;
end_import

begin_comment
comment|/**  * An {@link AsyncHandler} augmented with an {@link #onCompleted(Response)} convenience method which gets called  * when the {@link Response} has been fully received.  *  * @param<T>  Type of the value that will be returned by the associated {@link java.util.concurrent.Future}  */
end_comment

begin_class
DECL|class|AsyncCompletionHandler
specifier|public
specifier|abstract
class|class
name|AsyncCompletionHandler
parameter_list|<
name|T
parameter_list|>
implements|implements
name|AsyncHandler
argument_list|<
name|T
argument_list|>
block|{
DECL|field|log
specifier|private
specifier|final
specifier|static
name|ESLogger
name|log
init|=
name|Loggers
operator|.
name|getLogger
argument_list|(
name|AsyncCompletionHandlerBase
operator|.
name|class
argument_list|)
decl_stmt|;
DECL|field|bodies
specifier|private
specifier|final
name|Collection
argument_list|<
name|HttpResponseBodyPart
argument_list|<
name|T
argument_list|>
argument_list|>
name|bodies
init|=
name|Collections
operator|.
name|synchronizedCollection
argument_list|(
operator|new
name|ArrayList
argument_list|<
name|HttpResponseBodyPart
argument_list|<
name|T
argument_list|>
argument_list|>
argument_list|()
argument_list|)
decl_stmt|;
DECL|field|status
specifier|private
name|HttpResponseStatus
argument_list|<
name|T
argument_list|>
name|status
decl_stmt|;
DECL|field|headers
specifier|private
name|HttpResponseHeaders
argument_list|<
name|T
argument_list|>
name|headers
decl_stmt|;
comment|/**      * {@inheritDoc}      */
comment|/* @Override */
DECL|method|onBodyPartReceived
specifier|public
name|STATE
name|onBodyPartReceived
parameter_list|(
specifier|final
name|HttpResponseBodyPart
argument_list|<
name|T
argument_list|>
name|content
parameter_list|)
throws|throws
name|Exception
block|{
name|bodies
operator|.
name|add
argument_list|(
name|content
argument_list|)
expr_stmt|;
return|return
name|STATE
operator|.
name|CONTINUE
return|;
block|}
comment|/**      * {@inheritDoc}      */
comment|/* @Override */
DECL|method|onStatusReceived
specifier|public
specifier|final
name|STATE
name|onStatusReceived
parameter_list|(
specifier|final
name|HttpResponseStatus
argument_list|<
name|T
argument_list|>
name|status
parameter_list|)
throws|throws
name|Exception
block|{
name|this
operator|.
name|status
operator|=
name|status
expr_stmt|;
return|return
name|STATE
operator|.
name|CONTINUE
return|;
block|}
comment|/**      * {@inheritDoc}      */
comment|/* @Override */
DECL|method|onHeadersReceived
specifier|public
specifier|final
name|STATE
name|onHeadersReceived
parameter_list|(
specifier|final
name|HttpResponseHeaders
argument_list|<
name|T
argument_list|>
name|headers
parameter_list|)
throws|throws
name|Exception
block|{
name|this
operator|.
name|headers
operator|=
name|headers
expr_stmt|;
return|return
name|STATE
operator|.
name|CONTINUE
return|;
block|}
comment|/**      * {@inheritDoc}      */
comment|/* @Override */
DECL|method|onCompleted
specifier|public
specifier|final
name|T
name|onCompleted
parameter_list|()
throws|throws
name|Exception
block|{
return|return
name|onCompleted
argument_list|(
name|status
operator|==
literal|null
condition|?
literal|null
else|:
name|status
operator|.
name|provider
argument_list|()
operator|.
name|prepareResponse
argument_list|(
name|status
argument_list|,
name|headers
argument_list|,
name|bodies
argument_list|)
argument_list|)
return|;
block|}
comment|/**      * {@inheritDoc}      */
comment|/* @Override */
DECL|method|onThrowable
specifier|public
name|void
name|onThrowable
parameter_list|(
name|Throwable
name|t
parameter_list|)
block|{
if|if
condition|(
name|log
operator|.
name|isDebugEnabled
argument_list|()
condition|)
name|log
operator|.
name|debug
argument_list|(
name|t
operator|.
name|getMessage
argument_list|()
argument_list|,
name|t
argument_list|)
expr_stmt|;
block|}
comment|/**      * Invoked once the HTTP response has been fully read.      *      * @param response The {@link Response}      * @return Type of the value that will be returned by the associated {@link java.util.concurrent.Future}      */
DECL|method|onCompleted
specifier|abstract
specifier|public
name|T
name|onCompleted
parameter_list|(
name|Response
name|response
parameter_list|)
throws|throws
name|Exception
function_decl|;
block|}
end_class

end_unit

