begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Copyright 2010 Ning, Inc.  *  * Ning licenses this file to you under the Apache License, version 2.0  * (the "License"); you may not use this file except in compliance with the  * License.  You may obtain a copy of the License at:  *  *    http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT  * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the  * License for the specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
DECL|package|org.elasticsearch.util.http.client
package|package
name|org
operator|.
name|elasticsearch
operator|.
name|util
operator|.
name|http
operator|.
name|client
package|;
end_package

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|util
operator|.
name|http
operator|.
name|url
operator|.
name|Url
import|;
end_import

begin_comment
comment|/**  * Base class for callback class used by {@link org.elasticsearch.util.http.client.AsyncHandler}  */
end_comment

begin_class
DECL|class|HttpContent
specifier|public
class|class
name|HttpContent
parameter_list|<
name|R
parameter_list|>
block|{
DECL|field|response
specifier|protected
specifier|final
name|R
name|response
decl_stmt|;
DECL|field|provider
specifier|protected
specifier|final
name|AsyncHttpProvider
argument_list|<
name|R
argument_list|>
name|provider
decl_stmt|;
DECL|field|url
specifier|protected
specifier|final
name|Url
name|url
decl_stmt|;
DECL|method|HttpContent
specifier|protected
name|HttpContent
parameter_list|(
name|Url
name|url
parameter_list|,
name|R
name|response
parameter_list|,
name|AsyncHttpProvider
argument_list|<
name|R
argument_list|>
name|provider
parameter_list|)
block|{
name|this
operator|.
name|response
operator|=
name|response
expr_stmt|;
name|this
operator|.
name|provider
operator|=
name|provider
expr_stmt|;
name|this
operator|.
name|url
operator|=
name|url
expr_stmt|;
block|}
DECL|method|provider
specifier|protected
specifier|final
name|AsyncHttpProvider
argument_list|<
name|R
argument_list|>
name|provider
parameter_list|()
block|{
return|return
name|provider
return|;
block|}
DECL|method|getUrl
specifier|public
specifier|final
name|Url
name|getUrl
parameter_list|()
block|{
return|return
name|url
return|;
block|}
block|}
end_class

end_unit

