begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to Elasticsearch under one or more contributor  * license agreements. See the NOTICE file distributed with  * this work for additional information regarding copyright  * ownership. Elasticsearch licenses this file to you under  * the Apache License, Version 2.0 (the "License"); you may  * not use this file except in compliance with the License.  * You may obtain a copy of the License at  *  *    http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied.  See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
DECL|package|org.elasticsearch.repositories.blobstore
package|package
name|org
operator|.
name|elasticsearch
operator|.
name|repositories
operator|.
name|blobstore
package|;
end_package

begin_import
import|import
name|com
operator|.
name|fasterxml
operator|.
name|jackson
operator|.
name|core
operator|.
name|JsonParseException
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|ImmutableList
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|ImmutableMap
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|Maps
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|io
operator|.
name|ByteStreams
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|lucene
operator|.
name|store
operator|.
name|RateLimiter
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|lucene
operator|.
name|util
operator|.
name|IOUtils
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|ElasticsearchParseException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|cluster
operator|.
name|metadata
operator|.
name|IndexMetaData
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|cluster
operator|.
name|metadata
operator|.
name|MetaData
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|cluster
operator|.
name|metadata
operator|.
name|SnapshotId
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|common
operator|.
name|Strings
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|common
operator|.
name|blobstore
operator|.
name|BlobContainer
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|common
operator|.
name|blobstore
operator|.
name|BlobMetaData
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|common
operator|.
name|blobstore
operator|.
name|BlobPath
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|common
operator|.
name|blobstore
operator|.
name|BlobStore
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|common
operator|.
name|bytes
operator|.
name|BytesArray
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|common
operator|.
name|bytes
operator|.
name|BytesReference
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|common
operator|.
name|component
operator|.
name|AbstractLifecycleComponent
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|common
operator|.
name|compress
operator|.
name|CompressorFactory
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|common
operator|.
name|compress
operator|.
name|NotXContentException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|common
operator|.
name|io
operator|.
name|stream
operator|.
name|BytesStreamOutput
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|common
operator|.
name|io
operator|.
name|stream
operator|.
name|OutputStreamStreamOutput
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|common
operator|.
name|io
operator|.
name|stream
operator|.
name|StreamOutput
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|common
operator|.
name|metrics
operator|.
name|CounterMetric
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|common
operator|.
name|unit
operator|.
name|ByteSizeUnit
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|common
operator|.
name|unit
operator|.
name|ByteSizeValue
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|common
operator|.
name|xcontent
operator|.
name|ToXContent
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|common
operator|.
name|xcontent
operator|.
name|XContentBuilder
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|common
operator|.
name|xcontent
operator|.
name|XContentFactory
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|common
operator|.
name|xcontent
operator|.
name|XContentHelper
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|common
operator|.
name|xcontent
operator|.
name|XContentParser
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|common
operator|.
name|xcontent
operator|.
name|XContentType
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|index
operator|.
name|shard
operator|.
name|IndexShardException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|index
operator|.
name|shard
operator|.
name|ShardId
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|index
operator|.
name|snapshots
operator|.
name|IndexShardRepository
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|index
operator|.
name|snapshots
operator|.
name|blobstore
operator|.
name|BlobStoreIndexShardRepository
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|index
operator|.
name|snapshots
operator|.
name|blobstore
operator|.
name|BlobStoreIndexShardRepository
operator|.
name|RateLimiterListener
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|repositories
operator|.
name|Repository
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|repositories
operator|.
name|RepositoryException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|repositories
operator|.
name|RepositorySettings
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|repositories
operator|.
name|RepositoryVerificationException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|snapshots
operator|.
name|InvalidSnapshotNameException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|snapshots
operator|.
name|Snapshot
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|snapshots
operator|.
name|SnapshotCreationException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|snapshots
operator|.
name|SnapshotException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|snapshots
operator|.
name|SnapshotMissingException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|snapshots
operator|.
name|SnapshotShardFailure
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|FileNotFoundException
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|InputStream
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|OutputStream
import|;
end_import

begin_import
import|import
name|java
operator|.
name|nio
operator|.
name|file
operator|.
name|NoSuchFileException
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|ArrayList
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Map
import|;
end_import

begin_import
import|import static
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|Lists
operator|.
name|newArrayList
import|;
end_import

begin_comment
comment|/**  * BlobStore - based implementation of Snapshot Repository  *<p/>  * This repository works with any {@link BlobStore} implementation. The blobStore should be initialized in the derived  * class before {@link #doStart()} is called.  *<p/>  *<p/>  * BlobStoreRepository maintains the following structure in the blob store  *<pre>  * {@code  *   STORE_ROOT  *   |- index             - list of all snapshot name as JSON array  *   |- snapshot-20131010 - JSON serialized Snapshot for snapshot "20131010"  *   |- metadata-20131010 - JSON serialized MetaData for snapshot "20131010" (includes only global metadata)  *   |- snapshot-20131011 - JSON serialized Snapshot for snapshot "20131011"  *   |- metadata-20131011 - JSON serialized MetaData for snapshot "20131011"  *   .....  *   |- indices/ - data for all indices  *      |- foo/ - data for index "foo"  *      |  |- snapshot-20131010 - JSON Serialized IndexMetaData for index "foo"  *      |  |- 0/ - data for shard "0" of index "foo"  *      |  |  |- __1 \  *      |  |  |- __2 |  *      |  |  |- __3 |- files from different segments see snapshot-* for their mappings to real segment files  *      |  |  |- __4 |  *      |  |  |- __5 /  *      |  |  .....  *      |  |  |- snapshot-20131010 - JSON serialized BlobStoreIndexShardSnapshot for snapshot "20131010"  *      |  |  |- snapshot-20131011 - JSON serialized BlobStoreIndexShardSnapshot for snapshot "20131011"  *      |  |  *      |  |- 1/ - data for shard "1" of index "foo"  *      |  |  |- __1  *      |  |  .....  *      |  |  *      |  |-2/  *      |  ......  *      |  *      |- bar/ - data for index bar  *      ......  * }  *</pre>  */
end_comment

begin_class
DECL|class|BlobStoreRepository
specifier|public
specifier|abstract
class|class
name|BlobStoreRepository
extends|extends
name|AbstractLifecycleComponent
argument_list|<
name|Repository
argument_list|>
implements|implements
name|Repository
implements|,
name|RateLimiterListener
block|{
DECL|field|snapshotsBlobContainer
specifier|private
name|BlobContainer
name|snapshotsBlobContainer
decl_stmt|;
DECL|field|repositoryName
specifier|protected
specifier|final
name|String
name|repositoryName
decl_stmt|;
DECL|field|SNAPSHOT_PREFIX
specifier|private
specifier|static
specifier|final
name|String
name|SNAPSHOT_PREFIX
init|=
literal|"snapshot-"
decl_stmt|;
DECL|field|TEMP_SNAPSHOT_FILE_PREFIX
specifier|private
specifier|static
specifier|final
name|String
name|TEMP_SNAPSHOT_FILE_PREFIX
init|=
literal|"pending-"
decl_stmt|;
DECL|field|SNAPSHOTS_FILE
specifier|private
specifier|static
specifier|final
name|String
name|SNAPSHOTS_FILE
init|=
literal|"index"
decl_stmt|;
DECL|field|TESTS_FILE
specifier|private
specifier|static
specifier|final
name|String
name|TESTS_FILE
init|=
literal|"tests-"
decl_stmt|;
DECL|field|METADATA_PREFIX
specifier|private
specifier|static
specifier|final
name|String
name|METADATA_PREFIX
init|=
literal|"metadata-"
decl_stmt|;
DECL|field|indexShardRepository
specifier|private
specifier|final
name|BlobStoreIndexShardRepository
name|indexShardRepository
decl_stmt|;
DECL|field|snapshotOnlyFormatParams
specifier|private
specifier|final
name|ToXContent
operator|.
name|Params
name|snapshotOnlyFormatParams
decl_stmt|;
DECL|field|snapshotRateLimiter
specifier|private
specifier|final
name|RateLimiter
name|snapshotRateLimiter
decl_stmt|;
DECL|field|restoreRateLimiter
specifier|private
specifier|final
name|RateLimiter
name|restoreRateLimiter
decl_stmt|;
DECL|field|snapshotRateLimitingTimeInNanos
specifier|private
specifier|final
name|CounterMetric
name|snapshotRateLimitingTimeInNanos
init|=
operator|new
name|CounterMetric
argument_list|()
decl_stmt|;
DECL|field|restoreRateLimitingTimeInNanos
specifier|private
specifier|final
name|CounterMetric
name|restoreRateLimitingTimeInNanos
init|=
operator|new
name|CounterMetric
argument_list|()
decl_stmt|;
comment|/**      * Constructs new BlobStoreRepository      *      * @param repositoryName       repository name      * @param repositorySettings   repository settings      * @param indexShardRepository an instance of IndexShardRepository      */
DECL|method|BlobStoreRepository
specifier|protected
name|BlobStoreRepository
parameter_list|(
name|String
name|repositoryName
parameter_list|,
name|RepositorySettings
name|repositorySettings
parameter_list|,
name|IndexShardRepository
name|indexShardRepository
parameter_list|)
block|{
name|super
argument_list|(
name|repositorySettings
operator|.
name|globalSettings
argument_list|()
argument_list|)
expr_stmt|;
name|this
operator|.
name|repositoryName
operator|=
name|repositoryName
expr_stmt|;
name|this
operator|.
name|indexShardRepository
operator|=
operator|(
name|BlobStoreIndexShardRepository
operator|)
name|indexShardRepository
expr_stmt|;
name|Map
argument_list|<
name|String
argument_list|,
name|String
argument_list|>
name|snpashotOnlyParams
init|=
name|Maps
operator|.
name|newHashMap
argument_list|()
decl_stmt|;
name|snpashotOnlyParams
operator|.
name|put
argument_list|(
name|MetaData
operator|.
name|CONTEXT_MODE_PARAM
argument_list|,
name|MetaData
operator|.
name|CONTEXT_MODE_SNAPSHOT
argument_list|)
expr_stmt|;
name|snapshotOnlyFormatParams
operator|=
operator|new
name|ToXContent
operator|.
name|MapParams
argument_list|(
name|snpashotOnlyParams
argument_list|)
expr_stmt|;
name|snapshotRateLimiter
operator|=
name|getRateLimiter
argument_list|(
name|repositorySettings
argument_list|,
literal|"max_snapshot_bytes_per_sec"
argument_list|,
operator|new
name|ByteSizeValue
argument_list|(
literal|40
argument_list|,
name|ByteSizeUnit
operator|.
name|MB
argument_list|)
argument_list|)
expr_stmt|;
name|restoreRateLimiter
operator|=
name|getRateLimiter
argument_list|(
name|repositorySettings
argument_list|,
literal|"max_restore_bytes_per_sec"
argument_list|,
operator|new
name|ByteSizeValue
argument_list|(
literal|40
argument_list|,
name|ByteSizeUnit
operator|.
name|MB
argument_list|)
argument_list|)
expr_stmt|;
block|}
comment|/**      * {@inheritDoc}      */
annotation|@
name|Override
DECL|method|doStart
specifier|protected
name|void
name|doStart
parameter_list|()
block|{
name|this
operator|.
name|snapshotsBlobContainer
operator|=
name|blobStore
argument_list|()
operator|.
name|blobContainer
argument_list|(
name|basePath
argument_list|()
argument_list|)
expr_stmt|;
name|indexShardRepository
operator|.
name|initialize
argument_list|(
name|blobStore
argument_list|()
argument_list|,
name|basePath
argument_list|()
argument_list|,
name|chunkSize
argument_list|()
argument_list|,
name|snapshotRateLimiter
argument_list|,
name|restoreRateLimiter
argument_list|,
name|this
argument_list|,
name|isCompress
argument_list|()
argument_list|)
expr_stmt|;
block|}
comment|/**      * {@inheritDoc}      */
annotation|@
name|Override
DECL|method|doStop
specifier|protected
name|void
name|doStop
parameter_list|()
block|{     }
comment|/**      * {@inheritDoc}      */
annotation|@
name|Override
DECL|method|doClose
specifier|protected
name|void
name|doClose
parameter_list|()
block|{
try|try
block|{
name|blobStore
argument_list|()
operator|.
name|close
argument_list|()
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|Throwable
name|t
parameter_list|)
block|{
name|logger
operator|.
name|warn
argument_list|(
literal|"cannot close blob store"
argument_list|,
name|t
argument_list|)
expr_stmt|;
block|}
block|}
comment|/**      * Returns initialized and ready to use BlobStore      *<p/>      * This method is first called in the {@link #doStart()} method.      *      * @return blob store      */
DECL|method|blobStore
specifier|abstract
specifier|protected
name|BlobStore
name|blobStore
parameter_list|()
function_decl|;
comment|/**      * Returns base path of the repository      */
DECL|method|basePath
specifier|abstract
specifier|protected
name|BlobPath
name|basePath
parameter_list|()
function_decl|;
comment|/**      * Returns true if metadata and snapshot files should be compressed      *      * @return true if compression is needed      */
DECL|method|isCompress
specifier|protected
name|boolean
name|isCompress
parameter_list|()
block|{
return|return
literal|false
return|;
block|}
comment|/**      * Returns data file chunk size.      *<p/>      * This method should return null if no chunking is needed.      *      * @return chunk size      */
DECL|method|chunkSize
specifier|protected
name|ByteSizeValue
name|chunkSize
parameter_list|()
block|{
return|return
literal|null
return|;
block|}
comment|/**      * {@inheritDoc}      */
annotation|@
name|Override
DECL|method|initializeSnapshot
specifier|public
name|void
name|initializeSnapshot
parameter_list|(
name|SnapshotId
name|snapshotId
parameter_list|,
name|ImmutableList
argument_list|<
name|String
argument_list|>
name|indices
parameter_list|,
name|MetaData
name|metaData
parameter_list|)
block|{
try|try
block|{
name|String
name|snapshotBlobName
init|=
name|snapshotBlobName
argument_list|(
name|snapshotId
argument_list|)
decl_stmt|;
if|if
condition|(
name|snapshotsBlobContainer
operator|.
name|blobExists
argument_list|(
name|snapshotBlobName
argument_list|)
condition|)
block|{
throw|throw
operator|new
name|InvalidSnapshotNameException
argument_list|(
name|snapshotId
argument_list|,
literal|"snapshot with such name already exists"
argument_list|)
throw|;
block|}
comment|// Write Global MetaData
comment|// TODO: Check if metadata needs to be written
try|try
init|(
name|StreamOutput
name|output
init|=
name|compressIfNeeded
argument_list|(
name|snapshotsBlobContainer
operator|.
name|createOutput
argument_list|(
name|metaDataBlobName
argument_list|(
name|snapshotId
argument_list|)
argument_list|)
argument_list|)
init|)
block|{
name|writeGlobalMetaData
argument_list|(
name|metaData
argument_list|,
name|output
argument_list|)
expr_stmt|;
block|}
for|for
control|(
name|String
name|index
range|:
name|indices
control|)
block|{
specifier|final
name|IndexMetaData
name|indexMetaData
init|=
name|metaData
operator|.
name|index
argument_list|(
name|index
argument_list|)
decl_stmt|;
specifier|final
name|BlobPath
name|indexPath
init|=
name|basePath
argument_list|()
operator|.
name|add
argument_list|(
literal|"indices"
argument_list|)
operator|.
name|add
argument_list|(
name|index
argument_list|)
decl_stmt|;
specifier|final
name|BlobContainer
name|indexMetaDataBlobContainer
init|=
name|blobStore
argument_list|()
operator|.
name|blobContainer
argument_list|(
name|indexPath
argument_list|)
decl_stmt|;
try|try
init|(
name|StreamOutput
name|output
init|=
name|compressIfNeeded
argument_list|(
name|indexMetaDataBlobContainer
operator|.
name|createOutput
argument_list|(
name|snapshotBlobName
argument_list|(
name|snapshotId
argument_list|)
argument_list|)
argument_list|)
init|)
block|{
name|XContentBuilder
name|builder
init|=
name|XContentFactory
operator|.
name|contentBuilder
argument_list|(
name|XContentType
operator|.
name|JSON
argument_list|,
name|output
argument_list|)
decl_stmt|;
name|builder
operator|.
name|startObject
argument_list|()
expr_stmt|;
name|IndexMetaData
operator|.
name|Builder
operator|.
name|toXContent
argument_list|(
name|indexMetaData
argument_list|,
name|builder
argument_list|,
name|ToXContent
operator|.
name|EMPTY_PARAMS
argument_list|)
expr_stmt|;
name|builder
operator|.
name|endObject
argument_list|()
expr_stmt|;
name|builder
operator|.
name|close
argument_list|()
expr_stmt|;
block|}
block|}
block|}
catch|catch
parameter_list|(
name|IOException
name|ex
parameter_list|)
block|{
throw|throw
operator|new
name|SnapshotCreationException
argument_list|(
name|snapshotId
argument_list|,
name|ex
argument_list|)
throw|;
block|}
block|}
comment|/**      * {@inheritDoc}      */
annotation|@
name|Override
DECL|method|deleteSnapshot
specifier|public
name|void
name|deleteSnapshot
parameter_list|(
name|SnapshotId
name|snapshotId
parameter_list|)
block|{
name|ImmutableList
argument_list|<
name|String
argument_list|>
name|indices
init|=
name|ImmutableList
operator|.
name|of
argument_list|()
decl_stmt|;
try|try
block|{
name|indices
operator|=
name|readSnapshot
argument_list|(
name|snapshotId
argument_list|)
operator|.
name|indices
argument_list|()
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|SnapshotMissingException
name|ex
parameter_list|)
block|{
throw|throw
name|ex
throw|;
block|}
catch|catch
parameter_list|(
name|SnapshotException
decl||
name|ElasticsearchParseException
name|ex
parameter_list|)
block|{
name|logger
operator|.
name|warn
argument_list|(
literal|"cannot read snapshot file [{}]"
argument_list|,
name|ex
argument_list|,
name|snapshotId
argument_list|)
expr_stmt|;
block|}
name|MetaData
name|metaData
init|=
literal|null
decl_stmt|;
try|try
block|{
name|metaData
operator|=
name|readSnapshotMetaData
argument_list|(
name|snapshotId
argument_list|,
name|indices
argument_list|,
literal|true
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|IOException
decl||
name|SnapshotException
name|ex
parameter_list|)
block|{
name|logger
operator|.
name|warn
argument_list|(
literal|"cannot read metadata for snapshot [{}]"
argument_list|,
name|ex
argument_list|,
name|snapshotId
argument_list|)
expr_stmt|;
block|}
try|try
block|{
name|String
name|blobName
init|=
name|snapshotBlobName
argument_list|(
name|snapshotId
argument_list|)
decl_stmt|;
comment|// Delete snapshot file first so we wouldn't end up with partially deleted snapshot that looks OK
name|snapshotsBlobContainer
operator|.
name|deleteBlob
argument_list|(
name|blobName
argument_list|)
expr_stmt|;
name|snapshotsBlobContainer
operator|.
name|deleteBlob
argument_list|(
name|metaDataBlobName
argument_list|(
name|snapshotId
argument_list|)
argument_list|)
expr_stmt|;
comment|// Delete snapshot from the snapshot list
name|ImmutableList
argument_list|<
name|SnapshotId
argument_list|>
name|snapshotIds
init|=
name|snapshots
argument_list|()
decl_stmt|;
if|if
condition|(
name|snapshotIds
operator|.
name|contains
argument_list|(
name|snapshotId
argument_list|)
condition|)
block|{
name|ImmutableList
operator|.
name|Builder
argument_list|<
name|SnapshotId
argument_list|>
name|builder
init|=
name|ImmutableList
operator|.
name|builder
argument_list|()
decl_stmt|;
for|for
control|(
name|SnapshotId
name|id
range|:
name|snapshotIds
control|)
block|{
if|if
condition|(
operator|!
name|snapshotId
operator|.
name|equals
argument_list|(
name|id
argument_list|)
condition|)
block|{
name|builder
operator|.
name|add
argument_list|(
name|id
argument_list|)
expr_stmt|;
block|}
block|}
name|snapshotIds
operator|=
name|builder
operator|.
name|build
argument_list|()
expr_stmt|;
block|}
name|writeSnapshotList
argument_list|(
name|snapshotIds
argument_list|)
expr_stmt|;
comment|// Now delete all indices
for|for
control|(
name|String
name|index
range|:
name|indices
control|)
block|{
name|BlobPath
name|indexPath
init|=
name|basePath
argument_list|()
operator|.
name|add
argument_list|(
literal|"indices"
argument_list|)
operator|.
name|add
argument_list|(
name|index
argument_list|)
decl_stmt|;
name|BlobContainer
name|indexMetaDataBlobContainer
init|=
name|blobStore
argument_list|()
operator|.
name|blobContainer
argument_list|(
name|indexPath
argument_list|)
decl_stmt|;
try|try
block|{
name|indexMetaDataBlobContainer
operator|.
name|deleteBlob
argument_list|(
name|blobName
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|IOException
name|ex
parameter_list|)
block|{
name|logger
operator|.
name|warn
argument_list|(
literal|"[{}] failed to delete metadata for index [{}]"
argument_list|,
name|ex
argument_list|,
name|snapshotId
argument_list|,
name|index
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|metaData
operator|!=
literal|null
condition|)
block|{
name|IndexMetaData
name|indexMetaData
init|=
name|metaData
operator|.
name|index
argument_list|(
name|index
argument_list|)
decl_stmt|;
if|if
condition|(
name|indexMetaData
operator|!=
literal|null
condition|)
block|{
for|for
control|(
name|int
name|i
init|=
literal|0
init|;
name|i
operator|<
name|indexMetaData
operator|.
name|getNumberOfShards
argument_list|()
condition|;
name|i
operator|++
control|)
block|{
name|ShardId
name|shardId
init|=
operator|new
name|ShardId
argument_list|(
name|index
argument_list|,
name|i
argument_list|)
decl_stmt|;
try|try
block|{
name|indexShardRepository
operator|.
name|delete
argument_list|(
name|snapshotId
argument_list|,
name|shardId
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|IndexShardException
decl||
name|SnapshotException
name|ex
parameter_list|)
block|{
name|logger
operator|.
name|warn
argument_list|(
literal|"[{}] failed to delete shard data for shard [{}]"
argument_list|,
name|ex
argument_list|,
name|snapshotId
argument_list|,
name|shardId
argument_list|)
expr_stmt|;
block|}
block|}
block|}
block|}
block|}
block|}
catch|catch
parameter_list|(
name|IOException
name|ex
parameter_list|)
block|{
throw|throw
operator|new
name|RepositoryException
argument_list|(
name|this
operator|.
name|repositoryName
argument_list|,
literal|"failed to update snapshot in repository"
argument_list|,
name|ex
argument_list|)
throw|;
block|}
block|}
DECL|method|compressIfNeeded
specifier|private
name|StreamOutput
name|compressIfNeeded
parameter_list|(
name|OutputStream
name|output
parameter_list|)
throws|throws
name|IOException
block|{
return|return
name|toStreamOutput
argument_list|(
name|output
argument_list|,
name|isCompress
argument_list|()
argument_list|)
return|;
block|}
DECL|method|toStreamOutput
specifier|public
specifier|static
name|StreamOutput
name|toStreamOutput
parameter_list|(
name|OutputStream
name|output
parameter_list|,
name|boolean
name|compress
parameter_list|)
throws|throws
name|IOException
block|{
name|StreamOutput
name|out
init|=
literal|null
decl_stmt|;
name|boolean
name|success
init|=
literal|false
decl_stmt|;
try|try
block|{
name|out
operator|=
operator|new
name|OutputStreamStreamOutput
argument_list|(
name|output
argument_list|)
expr_stmt|;
if|if
condition|(
name|compress
condition|)
block|{
name|out
operator|=
name|CompressorFactory
operator|.
name|defaultCompressor
argument_list|()
operator|.
name|streamOutput
argument_list|(
name|out
argument_list|)
expr_stmt|;
block|}
name|success
operator|=
literal|true
expr_stmt|;
return|return
name|out
return|;
block|}
finally|finally
block|{
if|if
condition|(
operator|!
name|success
condition|)
block|{
name|IOUtils
operator|.
name|closeWhileHandlingException
argument_list|(
name|out
argument_list|,
name|output
argument_list|)
expr_stmt|;
block|}
block|}
block|}
comment|/**      * {@inheritDoc}      */
annotation|@
name|Override
DECL|method|finalizeSnapshot
specifier|public
name|Snapshot
name|finalizeSnapshot
parameter_list|(
name|SnapshotId
name|snapshotId
parameter_list|,
name|ImmutableList
argument_list|<
name|String
argument_list|>
name|indices
parameter_list|,
name|long
name|startTime
parameter_list|,
name|String
name|failure
parameter_list|,
name|int
name|totalShards
parameter_list|,
name|ImmutableList
argument_list|<
name|SnapshotShardFailure
argument_list|>
name|shardFailures
parameter_list|)
block|{
try|try
block|{
name|String
name|tempBlobName
init|=
name|tempSnapshotBlobName
argument_list|(
name|snapshotId
argument_list|)
decl_stmt|;
name|String
name|blobName
init|=
name|snapshotBlobName
argument_list|(
name|snapshotId
argument_list|)
decl_stmt|;
name|Snapshot
name|blobStoreSnapshot
init|=
operator|new
name|Snapshot
argument_list|(
name|snapshotId
operator|.
name|getSnapshot
argument_list|()
argument_list|,
name|indices
argument_list|,
name|startTime
argument_list|,
name|failure
argument_list|,
name|System
operator|.
name|currentTimeMillis
argument_list|()
argument_list|,
name|totalShards
argument_list|,
name|shardFailures
argument_list|)
decl_stmt|;
try|try
init|(
name|StreamOutput
name|output
init|=
name|compressIfNeeded
argument_list|(
name|snapshotsBlobContainer
operator|.
name|createOutput
argument_list|(
name|tempBlobName
argument_list|)
argument_list|)
init|)
block|{
name|writeSnapshot
argument_list|(
name|blobStoreSnapshot
argument_list|,
name|output
argument_list|)
expr_stmt|;
block|}
name|snapshotsBlobContainer
operator|.
name|move
argument_list|(
name|tempBlobName
argument_list|,
name|blobName
argument_list|)
expr_stmt|;
name|ImmutableList
argument_list|<
name|SnapshotId
argument_list|>
name|snapshotIds
init|=
name|snapshots
argument_list|()
decl_stmt|;
if|if
condition|(
operator|!
name|snapshotIds
operator|.
name|contains
argument_list|(
name|snapshotId
argument_list|)
condition|)
block|{
name|snapshotIds
operator|=
name|ImmutableList
operator|.
expr|<
name|SnapshotId
operator|>
name|builder
argument_list|()
operator|.
name|addAll
argument_list|(
name|snapshotIds
argument_list|)
operator|.
name|add
argument_list|(
name|snapshotId
argument_list|)
operator|.
name|build
argument_list|()
expr_stmt|;
block|}
name|writeSnapshotList
argument_list|(
name|snapshotIds
argument_list|)
expr_stmt|;
return|return
name|blobStoreSnapshot
return|;
block|}
catch|catch
parameter_list|(
name|IOException
name|ex
parameter_list|)
block|{
throw|throw
operator|new
name|RepositoryException
argument_list|(
name|this
operator|.
name|repositoryName
argument_list|,
literal|"failed to update snapshot in repository"
argument_list|,
name|ex
argument_list|)
throw|;
block|}
block|}
comment|/**      * {@inheritDoc}      */
annotation|@
name|Override
DECL|method|snapshots
specifier|public
name|ImmutableList
argument_list|<
name|SnapshotId
argument_list|>
name|snapshots
parameter_list|()
block|{
try|try
block|{
name|List
argument_list|<
name|SnapshotId
argument_list|>
name|snapshots
init|=
name|newArrayList
argument_list|()
decl_stmt|;
name|ImmutableMap
argument_list|<
name|String
argument_list|,
name|BlobMetaData
argument_list|>
name|blobs
decl_stmt|;
try|try
block|{
name|blobs
operator|=
name|snapshotsBlobContainer
operator|.
name|listBlobsByPrefix
argument_list|(
name|SNAPSHOT_PREFIX
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|UnsupportedOperationException
name|ex
parameter_list|)
block|{
comment|// Fall back in case listBlobsByPrefix isn't supported by the blob store
return|return
name|readSnapshotList
argument_list|()
return|;
block|}
name|int
name|prefixLength
init|=
name|SNAPSHOT_PREFIX
operator|.
name|length
argument_list|()
decl_stmt|;
for|for
control|(
name|BlobMetaData
name|md
range|:
name|blobs
operator|.
name|values
argument_list|()
control|)
block|{
name|String
name|name
init|=
name|md
operator|.
name|name
argument_list|()
operator|.
name|substring
argument_list|(
name|prefixLength
argument_list|)
decl_stmt|;
name|snapshots
operator|.
name|add
argument_list|(
operator|new
name|SnapshotId
argument_list|(
name|repositoryName
argument_list|,
name|name
argument_list|)
argument_list|)
expr_stmt|;
block|}
return|return
name|ImmutableList
operator|.
name|copyOf
argument_list|(
name|snapshots
argument_list|)
return|;
block|}
catch|catch
parameter_list|(
name|IOException
name|ex
parameter_list|)
block|{
throw|throw
operator|new
name|RepositoryException
argument_list|(
name|repositoryName
argument_list|,
literal|"failed to list snapshots in repository"
argument_list|,
name|ex
argument_list|)
throw|;
block|}
block|}
comment|/**      * {@inheritDoc}      */
annotation|@
name|Override
DECL|method|readSnapshotMetaData
specifier|public
name|MetaData
name|readSnapshotMetaData
parameter_list|(
name|SnapshotId
name|snapshotId
parameter_list|,
name|ImmutableList
argument_list|<
name|String
argument_list|>
name|indices
parameter_list|)
throws|throws
name|IOException
block|{
return|return
name|readSnapshotMetaData
argument_list|(
name|snapshotId
argument_list|,
name|indices
argument_list|,
literal|false
argument_list|)
return|;
block|}
comment|/**      * {@inheritDoc}      */
annotation|@
name|Override
DECL|method|readSnapshot
specifier|public
name|Snapshot
name|readSnapshot
parameter_list|(
name|SnapshotId
name|snapshotId
parameter_list|)
block|{
try|try
block|{
try|try
init|(
name|InputStream
name|blob
init|=
name|snapshotsBlobContainer
operator|.
name|openInput
argument_list|(
name|snapshotBlobName
argument_list|(
name|snapshotId
argument_list|)
argument_list|)
init|)
block|{
return|return
name|readSnapshot
argument_list|(
name|ByteStreams
operator|.
name|toByteArray
argument_list|(
name|blob
argument_list|)
argument_list|)
return|;
block|}
block|}
catch|catch
parameter_list|(
name|FileNotFoundException
decl||
name|NoSuchFileException
name|ex
parameter_list|)
block|{
throw|throw
operator|new
name|SnapshotMissingException
argument_list|(
name|snapshotId
argument_list|,
name|ex
argument_list|)
throw|;
block|}
catch|catch
parameter_list|(
name|IOException
decl||
name|NotXContentException
name|ex
parameter_list|)
block|{
throw|throw
operator|new
name|SnapshotException
argument_list|(
name|snapshotId
argument_list|,
literal|"failed to get snapshots"
argument_list|,
name|ex
argument_list|)
throw|;
block|}
block|}
DECL|method|readSnapshotMetaData
specifier|private
name|MetaData
name|readSnapshotMetaData
parameter_list|(
name|SnapshotId
name|snapshotId
parameter_list|,
name|ImmutableList
argument_list|<
name|String
argument_list|>
name|indices
parameter_list|,
name|boolean
name|ignoreIndexErrors
parameter_list|)
throws|throws
name|IOException
block|{
name|MetaData
name|metaData
decl_stmt|;
try|try
init|(
name|InputStream
name|blob
init|=
name|snapshotsBlobContainer
operator|.
name|openInput
argument_list|(
name|metaDataBlobName
argument_list|(
name|snapshotId
argument_list|)
argument_list|)
init|)
block|{
name|byte
index|[]
name|data
init|=
name|ByteStreams
operator|.
name|toByteArray
argument_list|(
name|blob
argument_list|)
decl_stmt|;
name|metaData
operator|=
name|readMetaData
argument_list|(
name|data
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|FileNotFoundException
decl||
name|NoSuchFileException
name|ex
parameter_list|)
block|{
throw|throw
operator|new
name|SnapshotMissingException
argument_list|(
name|snapshotId
argument_list|,
name|ex
argument_list|)
throw|;
block|}
catch|catch
parameter_list|(
name|IOException
name|ex
parameter_list|)
block|{
throw|throw
operator|new
name|SnapshotException
argument_list|(
name|snapshotId
argument_list|,
literal|"failed to get snapshots"
argument_list|,
name|ex
argument_list|)
throw|;
block|}
name|MetaData
operator|.
name|Builder
name|metaDataBuilder
init|=
name|MetaData
operator|.
name|builder
argument_list|(
name|metaData
argument_list|)
decl_stmt|;
for|for
control|(
name|String
name|index
range|:
name|indices
control|)
block|{
name|BlobPath
name|indexPath
init|=
name|basePath
argument_list|()
operator|.
name|add
argument_list|(
literal|"indices"
argument_list|)
operator|.
name|add
argument_list|(
name|index
argument_list|)
decl_stmt|;
name|BlobContainer
name|indexMetaDataBlobContainer
init|=
name|blobStore
argument_list|()
operator|.
name|blobContainer
argument_list|(
name|indexPath
argument_list|)
decl_stmt|;
try|try
init|(
name|InputStream
name|blob
init|=
name|indexMetaDataBlobContainer
operator|.
name|openInput
argument_list|(
name|snapshotBlobName
argument_list|(
name|snapshotId
argument_list|)
argument_list|)
init|)
block|{
name|byte
index|[]
name|data
init|=
name|ByteStreams
operator|.
name|toByteArray
argument_list|(
name|blob
argument_list|)
decl_stmt|;
try|try
init|(
name|XContentParser
name|parser
init|=
name|XContentHelper
operator|.
name|createParser
argument_list|(
operator|new
name|BytesArray
argument_list|(
name|data
argument_list|)
argument_list|)
init|)
block|{
name|XContentParser
operator|.
name|Token
name|token
decl_stmt|;
if|if
condition|(
operator|(
name|token
operator|=
name|parser
operator|.
name|nextToken
argument_list|()
operator|)
operator|==
name|XContentParser
operator|.
name|Token
operator|.
name|START_OBJECT
condition|)
block|{
name|IndexMetaData
name|indexMetaData
init|=
name|IndexMetaData
operator|.
name|Builder
operator|.
name|fromXContent
argument_list|(
name|parser
argument_list|)
decl_stmt|;
if|if
condition|(
operator|(
name|token
operator|=
name|parser
operator|.
name|nextToken
argument_list|()
operator|)
operator|==
name|XContentParser
operator|.
name|Token
operator|.
name|END_OBJECT
condition|)
block|{
name|metaDataBuilder
operator|.
name|put
argument_list|(
name|indexMetaData
argument_list|,
literal|false
argument_list|)
expr_stmt|;
continue|continue;
block|}
block|}
if|if
condition|(
operator|!
name|ignoreIndexErrors
condition|)
block|{
throw|throw
operator|new
name|ElasticsearchParseException
argument_list|(
literal|"unexpected token  ["
operator|+
name|token
operator|+
literal|"]"
argument_list|)
throw|;
block|}
else|else
block|{
name|logger
operator|.
name|warn
argument_list|(
literal|"[{}] [{}] unexpected token while reading snapshot metadata [{}]"
argument_list|,
name|snapshotId
argument_list|,
name|index
argument_list|,
name|token
argument_list|)
expr_stmt|;
block|}
block|}
block|}
catch|catch
parameter_list|(
name|IOException
name|ex
parameter_list|)
block|{
if|if
condition|(
operator|!
name|ignoreIndexErrors
condition|)
block|{
throw|throw
operator|new
name|SnapshotException
argument_list|(
name|snapshotId
argument_list|,
literal|"failed to read metadata"
argument_list|,
name|ex
argument_list|)
throw|;
block|}
else|else
block|{
name|logger
operator|.
name|warn
argument_list|(
literal|"[{}] [{}] failed to read metadata for index"
argument_list|,
name|snapshotId
argument_list|,
name|index
argument_list|,
name|ex
argument_list|)
expr_stmt|;
block|}
block|}
block|}
return|return
name|metaDataBuilder
operator|.
name|build
argument_list|()
return|;
block|}
comment|/**      * Configures RateLimiter based on repository and global settings      *      * @param repositorySettings repository settings      * @param setting            setting to use to configure rate limiter      * @param defaultRate        default limiting rate      * @return rate limiter or null of no throttling is needed      */
DECL|method|getRateLimiter
specifier|private
name|RateLimiter
name|getRateLimiter
parameter_list|(
name|RepositorySettings
name|repositorySettings
parameter_list|,
name|String
name|setting
parameter_list|,
name|ByteSizeValue
name|defaultRate
parameter_list|)
block|{
name|ByteSizeValue
name|maxSnapshotBytesPerSec
init|=
name|repositorySettings
operator|.
name|settings
argument_list|()
operator|.
name|getAsBytesSize
argument_list|(
name|setting
argument_list|,
name|settings
operator|.
name|getAsBytesSize
argument_list|(
name|setting
argument_list|,
name|defaultRate
argument_list|)
argument_list|)
decl_stmt|;
if|if
condition|(
name|maxSnapshotBytesPerSec
operator|.
name|bytes
argument_list|()
operator|<=
literal|0
condition|)
block|{
return|return
literal|null
return|;
block|}
else|else
block|{
return|return
operator|new
name|RateLimiter
operator|.
name|SimpleRateLimiter
argument_list|(
name|maxSnapshotBytesPerSec
operator|.
name|mbFrac
argument_list|()
argument_list|)
return|;
block|}
block|}
comment|/**      * Parses JSON containing snapshot description      *      * @param data snapshot description in JSON format      * @return parsed snapshot description      * @throws IOException parse exceptions      */
DECL|method|readSnapshot
specifier|public
name|Snapshot
name|readSnapshot
parameter_list|(
name|byte
index|[]
name|data
parameter_list|)
throws|throws
name|IOException
block|{
try|try
init|(
name|XContentParser
name|parser
init|=
name|XContentHelper
operator|.
name|createParser
argument_list|(
operator|new
name|BytesArray
argument_list|(
name|data
argument_list|)
argument_list|)
init|)
block|{
name|XContentParser
operator|.
name|Token
name|token
decl_stmt|;
if|if
condition|(
operator|(
name|token
operator|=
name|parser
operator|.
name|nextToken
argument_list|()
operator|)
operator|==
name|XContentParser
operator|.
name|Token
operator|.
name|START_OBJECT
condition|)
block|{
if|if
condition|(
operator|(
name|token
operator|=
name|parser
operator|.
name|nextToken
argument_list|()
operator|)
operator|==
name|XContentParser
operator|.
name|Token
operator|.
name|FIELD_NAME
condition|)
block|{
name|parser
operator|.
name|nextToken
argument_list|()
expr_stmt|;
name|Snapshot
name|snapshot
init|=
name|Snapshot
operator|.
name|fromXContent
argument_list|(
name|parser
argument_list|)
decl_stmt|;
if|if
condition|(
operator|(
name|token
operator|=
name|parser
operator|.
name|nextToken
argument_list|()
operator|)
operator|==
name|XContentParser
operator|.
name|Token
operator|.
name|END_OBJECT
condition|)
block|{
return|return
name|snapshot
return|;
block|}
block|}
block|}
throw|throw
operator|new
name|ElasticsearchParseException
argument_list|(
literal|"unexpected token  ["
operator|+
name|token
operator|+
literal|"]"
argument_list|)
throw|;
block|}
catch|catch
parameter_list|(
name|JsonParseException
name|ex
parameter_list|)
block|{
throw|throw
operator|new
name|ElasticsearchParseException
argument_list|(
literal|"failed to read snapshot"
argument_list|,
name|ex
argument_list|)
throw|;
block|}
block|}
comment|/**      * Parses JSON containing cluster metadata      *      * @param data cluster metadata in JSON format      * @return parsed metadata      * @throws IOException parse exceptions      */
DECL|method|readMetaData
specifier|private
name|MetaData
name|readMetaData
parameter_list|(
name|byte
index|[]
name|data
parameter_list|)
throws|throws
name|IOException
block|{
try|try
init|(
name|XContentParser
name|parser
init|=
name|XContentHelper
operator|.
name|createParser
argument_list|(
operator|new
name|BytesArray
argument_list|(
name|data
argument_list|)
argument_list|)
init|)
block|{
name|XContentParser
operator|.
name|Token
name|token
decl_stmt|;
if|if
condition|(
operator|(
name|token
operator|=
name|parser
operator|.
name|nextToken
argument_list|()
operator|)
operator|==
name|XContentParser
operator|.
name|Token
operator|.
name|START_OBJECT
condition|)
block|{
if|if
condition|(
operator|(
name|token
operator|=
name|parser
operator|.
name|nextToken
argument_list|()
operator|)
operator|==
name|XContentParser
operator|.
name|Token
operator|.
name|FIELD_NAME
condition|)
block|{
name|parser
operator|.
name|nextToken
argument_list|()
expr_stmt|;
name|MetaData
name|metaData
init|=
name|MetaData
operator|.
name|Builder
operator|.
name|fromXContent
argument_list|(
name|parser
argument_list|)
decl_stmt|;
if|if
condition|(
operator|(
name|token
operator|=
name|parser
operator|.
name|nextToken
argument_list|()
operator|)
operator|==
name|XContentParser
operator|.
name|Token
operator|.
name|END_OBJECT
condition|)
block|{
return|return
name|metaData
return|;
block|}
block|}
block|}
throw|throw
operator|new
name|ElasticsearchParseException
argument_list|(
literal|"unexpected token  ["
operator|+
name|token
operator|+
literal|"]"
argument_list|)
throw|;
block|}
block|}
comment|/**      * Returns name of snapshot blob      *      * @param snapshotId snapshot id      * @return name of snapshot blob      */
DECL|method|snapshotBlobName
specifier|private
name|String
name|snapshotBlobName
parameter_list|(
name|SnapshotId
name|snapshotId
parameter_list|)
block|{
return|return
name|SNAPSHOT_PREFIX
operator|+
name|snapshotId
operator|.
name|getSnapshot
argument_list|()
return|;
block|}
comment|/**      * Returns temporary name of snapshot blob      *      * @param snapshotId snapshot id      * @return name of snapshot blob      */
DECL|method|tempSnapshotBlobName
specifier|private
name|String
name|tempSnapshotBlobName
parameter_list|(
name|SnapshotId
name|snapshotId
parameter_list|)
block|{
return|return
name|TEMP_SNAPSHOT_FILE_PREFIX
operator|+
name|snapshotId
operator|.
name|getSnapshot
argument_list|()
return|;
block|}
comment|/**      * Returns name of metadata blob      *      * @param snapshotId snapshot id      * @return name of metadata blob      */
DECL|method|metaDataBlobName
specifier|private
name|String
name|metaDataBlobName
parameter_list|(
name|SnapshotId
name|snapshotId
parameter_list|)
block|{
return|return
name|METADATA_PREFIX
operator|+
name|snapshotId
operator|.
name|getSnapshot
argument_list|()
return|;
block|}
comment|/**      * Serializes Snapshot into JSON      *      * @param snapshot - snapshot description      * @return BytesStreamOutput representing JSON serialized Snapshot      * @throws IOException      */
DECL|method|writeSnapshot
specifier|private
name|void
name|writeSnapshot
parameter_list|(
name|Snapshot
name|snapshot
parameter_list|,
name|StreamOutput
name|outputStream
parameter_list|)
throws|throws
name|IOException
block|{
name|XContentBuilder
name|builder
init|=
name|XContentFactory
operator|.
name|contentBuilder
argument_list|(
name|XContentType
operator|.
name|JSON
argument_list|,
name|outputStream
argument_list|)
decl_stmt|;
name|builder
operator|.
name|startObject
argument_list|()
expr_stmt|;
name|snapshot
operator|.
name|toXContent
argument_list|(
name|builder
argument_list|,
name|snapshotOnlyFormatParams
argument_list|)
expr_stmt|;
name|builder
operator|.
name|endObject
argument_list|()
expr_stmt|;
name|builder
operator|.
name|flush
argument_list|()
expr_stmt|;
block|}
comment|/**      * Serializes global MetaData into JSON      *      * @param metaData - metaData      * @return BytesStreamOutput representing JSON serialized global MetaData      * @throws IOException      */
DECL|method|writeGlobalMetaData
specifier|private
name|void
name|writeGlobalMetaData
parameter_list|(
name|MetaData
name|metaData
parameter_list|,
name|StreamOutput
name|outputStream
parameter_list|)
throws|throws
name|IOException
block|{
name|XContentBuilder
name|builder
init|=
name|XContentFactory
operator|.
name|contentBuilder
argument_list|(
name|XContentType
operator|.
name|JSON
argument_list|,
name|outputStream
argument_list|)
decl_stmt|;
name|builder
operator|.
name|startObject
argument_list|()
expr_stmt|;
name|MetaData
operator|.
name|Builder
operator|.
name|toXContent
argument_list|(
name|metaData
argument_list|,
name|builder
argument_list|,
name|snapshotOnlyFormatParams
argument_list|)
expr_stmt|;
name|builder
operator|.
name|endObject
argument_list|()
expr_stmt|;
name|builder
operator|.
name|flush
argument_list|()
expr_stmt|;
block|}
comment|/**      * Writes snapshot index file      *<p/>      * This file can be used by read-only repositories that are unable to list files in the repository      *      * @param snapshots list of snapshot ids      * @throws IOException I/O errors      */
DECL|method|writeSnapshotList
specifier|protected
name|void
name|writeSnapshotList
parameter_list|(
name|ImmutableList
argument_list|<
name|SnapshotId
argument_list|>
name|snapshots
parameter_list|)
throws|throws
name|IOException
block|{
name|BytesStreamOutput
name|bStream
init|=
operator|new
name|BytesStreamOutput
argument_list|()
decl_stmt|;
name|StreamOutput
name|stream
init|=
name|compressIfNeeded
argument_list|(
name|bStream
argument_list|)
decl_stmt|;
name|XContentBuilder
name|builder
init|=
name|XContentFactory
operator|.
name|contentBuilder
argument_list|(
name|XContentType
operator|.
name|JSON
argument_list|,
name|stream
argument_list|)
decl_stmt|;
name|builder
operator|.
name|startObject
argument_list|()
expr_stmt|;
name|builder
operator|.
name|startArray
argument_list|(
literal|"snapshots"
argument_list|)
expr_stmt|;
for|for
control|(
name|SnapshotId
name|snapshot
range|:
name|snapshots
control|)
block|{
name|builder
operator|.
name|value
argument_list|(
name|snapshot
operator|.
name|getSnapshot
argument_list|()
argument_list|)
expr_stmt|;
block|}
name|builder
operator|.
name|endArray
argument_list|()
expr_stmt|;
name|builder
operator|.
name|endObject
argument_list|()
expr_stmt|;
name|builder
operator|.
name|close
argument_list|()
expr_stmt|;
name|BytesReference
name|bRef
init|=
name|bStream
operator|.
name|bytes
argument_list|()
decl_stmt|;
try|try
init|(
name|OutputStream
name|output
init|=
name|snapshotsBlobContainer
operator|.
name|createOutput
argument_list|(
name|SNAPSHOTS_FILE
argument_list|)
init|)
block|{
name|bRef
operator|.
name|writeTo
argument_list|(
name|output
argument_list|)
expr_stmt|;
block|}
block|}
comment|/**      * Reads snapshot index file      *<p/>      * This file can be used by read-only repositories that are unable to list files in the repository      *      * @return list of snapshots in the repository      * @throws IOException I/O errors      */
DECL|method|readSnapshotList
specifier|protected
name|ImmutableList
argument_list|<
name|SnapshotId
argument_list|>
name|readSnapshotList
parameter_list|()
throws|throws
name|IOException
block|{
try|try
init|(
name|InputStream
name|blob
init|=
name|snapshotsBlobContainer
operator|.
name|openInput
argument_list|(
name|SNAPSHOTS_FILE
argument_list|)
init|)
block|{
specifier|final
name|byte
index|[]
name|data
init|=
name|ByteStreams
operator|.
name|toByteArray
argument_list|(
name|blob
argument_list|)
decl_stmt|;
name|ArrayList
argument_list|<
name|SnapshotId
argument_list|>
name|snapshots
init|=
operator|new
name|ArrayList
argument_list|<>
argument_list|()
decl_stmt|;
try|try
init|(
name|XContentParser
name|parser
init|=
name|XContentHelper
operator|.
name|createParser
argument_list|(
operator|new
name|BytesArray
argument_list|(
name|data
argument_list|)
argument_list|)
init|)
block|{
if|if
condition|(
name|parser
operator|.
name|nextToken
argument_list|()
operator|==
name|XContentParser
operator|.
name|Token
operator|.
name|START_OBJECT
condition|)
block|{
if|if
condition|(
name|parser
operator|.
name|nextToken
argument_list|()
operator|==
name|XContentParser
operator|.
name|Token
operator|.
name|FIELD_NAME
condition|)
block|{
name|String
name|currentFieldName
init|=
name|parser
operator|.
name|currentName
argument_list|()
decl_stmt|;
if|if
condition|(
literal|"snapshots"
operator|.
name|equals
argument_list|(
name|currentFieldName
argument_list|)
condition|)
block|{
if|if
condition|(
name|parser
operator|.
name|nextToken
argument_list|()
operator|==
name|XContentParser
operator|.
name|Token
operator|.
name|START_ARRAY
condition|)
block|{
while|while
condition|(
name|parser
operator|.
name|nextToken
argument_list|()
operator|!=
name|XContentParser
operator|.
name|Token
operator|.
name|END_ARRAY
condition|)
block|{
name|snapshots
operator|.
name|add
argument_list|(
operator|new
name|SnapshotId
argument_list|(
name|repositoryName
argument_list|,
name|parser
operator|.
name|text
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
block|}
block|}
block|}
block|}
block|}
block|}
return|return
name|ImmutableList
operator|.
name|copyOf
argument_list|(
name|snapshots
argument_list|)
return|;
block|}
block|}
annotation|@
name|Override
DECL|method|onRestorePause
specifier|public
name|void
name|onRestorePause
parameter_list|(
name|long
name|nanos
parameter_list|)
block|{
name|restoreRateLimitingTimeInNanos
operator|.
name|inc
argument_list|(
name|nanos
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
DECL|method|onSnapshotPause
specifier|public
name|void
name|onSnapshotPause
parameter_list|(
name|long
name|nanos
parameter_list|)
block|{
name|snapshotRateLimitingTimeInNanos
operator|.
name|inc
argument_list|(
name|nanos
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
DECL|method|snapshotThrottleTimeInNanos
specifier|public
name|long
name|snapshotThrottleTimeInNanos
parameter_list|()
block|{
return|return
name|snapshotRateLimitingTimeInNanos
operator|.
name|count
argument_list|()
return|;
block|}
annotation|@
name|Override
DECL|method|restoreThrottleTimeInNanos
specifier|public
name|long
name|restoreThrottleTimeInNanos
parameter_list|()
block|{
return|return
name|restoreRateLimitingTimeInNanos
operator|.
name|count
argument_list|()
return|;
block|}
annotation|@
name|Override
DECL|method|startVerification
specifier|public
name|String
name|startVerification
parameter_list|()
block|{
try|try
block|{
name|String
name|seed
init|=
name|Strings
operator|.
name|randomBase64UUID
argument_list|()
decl_stmt|;
name|byte
index|[]
name|testBytes
init|=
name|Strings
operator|.
name|toUTF8Bytes
argument_list|(
name|seed
argument_list|)
decl_stmt|;
name|String
name|blobName
init|=
name|testBlobPrefix
argument_list|(
name|seed
argument_list|)
operator|+
literal|"-master"
decl_stmt|;
try|try
init|(
name|OutputStream
name|outputStream
init|=
name|snapshotsBlobContainer
operator|.
name|createOutput
argument_list|(
name|blobName
operator|+
literal|"-temp"
argument_list|)
init|)
block|{
name|outputStream
operator|.
name|write
argument_list|(
name|testBytes
argument_list|)
expr_stmt|;
block|}
comment|// Make sure that move is supported
name|snapshotsBlobContainer
operator|.
name|move
argument_list|(
name|blobName
operator|+
literal|"-temp"
argument_list|,
name|blobName
argument_list|)
expr_stmt|;
return|return
name|seed
return|;
block|}
catch|catch
parameter_list|(
name|IOException
name|exp
parameter_list|)
block|{
throw|throw
operator|new
name|RepositoryVerificationException
argument_list|(
name|repositoryName
argument_list|,
literal|"path "
operator|+
name|basePath
argument_list|()
operator|+
literal|" is not accessible on master node"
argument_list|,
name|exp
argument_list|)
throw|;
block|}
block|}
annotation|@
name|Override
DECL|method|endVerification
specifier|public
name|void
name|endVerification
parameter_list|(
name|String
name|seed
parameter_list|)
block|{
try|try
block|{
name|snapshotsBlobContainer
operator|.
name|deleteBlobsByPrefix
argument_list|(
name|testBlobPrefix
argument_list|(
name|seed
argument_list|)
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|IOException
name|exp
parameter_list|)
block|{
throw|throw
operator|new
name|RepositoryVerificationException
argument_list|(
name|repositoryName
argument_list|,
literal|"cannot delete test data at "
operator|+
name|basePath
argument_list|()
argument_list|,
name|exp
argument_list|)
throw|;
block|}
block|}
DECL|method|testBlobPrefix
specifier|public
specifier|static
name|String
name|testBlobPrefix
parameter_list|(
name|String
name|seed
parameter_list|)
block|{
return|return
name|TESTS_FILE
operator|+
name|seed
return|;
block|}
block|}
end_class

end_unit

