begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to Elastic Search and Shay Banon under one  * or more contributor license agreements.  See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership. Elastic Search licenses this  * file to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License.  You may obtain a copy of the License at  *  *    http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied.  See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
DECL|package|org.elasticsearch.index.field
package|package
name|org
operator|.
name|elasticsearch
operator|.
name|index
operator|.
name|field
package|;
end_package

begin_comment
comment|/**  * @author kimchy (shay.banon)  */
end_comment

begin_class
DECL|class|NumericDocFieldData
specifier|public
class|class
name|NumericDocFieldData
parameter_list|<
name|T
extends|extends
name|NumericFieldData
parameter_list|>
extends|extends
name|DocFieldData
argument_list|<
name|T
argument_list|>
block|{
DECL|method|NumericDocFieldData
specifier|public
name|NumericDocFieldData
parameter_list|(
name|T
name|fieldData
parameter_list|)
block|{
name|super
argument_list|(
name|fieldData
argument_list|)
expr_stmt|;
block|}
DECL|method|getIntValue
specifier|public
name|int
name|getIntValue
parameter_list|()
block|{
return|return
name|fieldData
operator|.
name|intValue
argument_list|(
name|docId
argument_list|)
return|;
block|}
DECL|method|getLongValue
specifier|public
name|long
name|getLongValue
parameter_list|()
block|{
return|return
name|fieldData
operator|.
name|longValue
argument_list|(
name|docId
argument_list|)
return|;
block|}
DECL|method|getFloatValue
specifier|public
name|float
name|getFloatValue
parameter_list|()
block|{
return|return
name|fieldData
operator|.
name|floatValue
argument_list|(
name|docId
argument_list|)
return|;
block|}
DECL|method|getDoubleValue
specifier|public
name|double
name|getDoubleValue
parameter_list|()
block|{
return|return
name|fieldData
operator|.
name|doubleValue
argument_list|(
name|docId
argument_list|)
return|;
block|}
DECL|method|getShortValue
specifier|public
name|short
name|getShortValue
parameter_list|()
block|{
return|return
name|fieldData
operator|.
name|shortValue
argument_list|(
name|docId
argument_list|)
return|;
block|}
DECL|method|getByteValue
specifier|public
name|byte
name|getByteValue
parameter_list|()
block|{
return|return
name|fieldData
operator|.
name|byteValue
argument_list|(
name|docId
argument_list|)
return|;
block|}
DECL|method|getDoubleValues
specifier|public
name|double
index|[]
name|getDoubleValues
parameter_list|()
block|{
return|return
name|fieldData
operator|.
name|doubleValues
argument_list|(
name|docId
argument_list|)
return|;
block|}
block|}
end_class

end_unit

