begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to Elasticsearch under one or more contributor  * license agreements. See the NOTICE file distributed with  * this work for additional information regarding copyright  * ownership. Elasticsearch licenses this file to you under  * the Apache License, Version 2.0 (the "License"); you may  * not use this file except in compliance with the License.  * You may obtain a copy of the License at  *  *    http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied.  See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
DECL|package|org.elasticsearch.action.admin.indices.rollover
package|package
name|org
operator|.
name|elasticsearch
operator|.
name|action
operator|.
name|admin
operator|.
name|indices
operator|.
name|rollover
package|;
end_package

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|action
operator|.
name|admin
operator|.
name|indices
operator|.
name|alias
operator|.
name|Alias
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|action
operator|.
name|support
operator|.
name|master
operator|.
name|MasterNodeOperationRequestBuilder
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|client
operator|.
name|ElasticsearchClient
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|common
operator|.
name|settings
operator|.
name|Settings
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|common
operator|.
name|unit
operator|.
name|TimeValue
import|;
end_import

begin_comment
comment|/**  * TODO: Documentation  */
end_comment

begin_class
DECL|class|RolloverRequestBuilder
specifier|public
class|class
name|RolloverRequestBuilder
extends|extends
name|MasterNodeOperationRequestBuilder
argument_list|<
name|RolloverRequest
argument_list|,
name|RolloverResponse
argument_list|,
name|RolloverRequestBuilder
argument_list|>
block|{
DECL|method|RolloverRequestBuilder
specifier|public
name|RolloverRequestBuilder
parameter_list|(
name|ElasticsearchClient
name|client
parameter_list|,
name|RolloverAction
name|action
parameter_list|)
block|{
name|super
argument_list|(
name|client
argument_list|,
name|action
argument_list|,
operator|new
name|RolloverRequest
argument_list|()
argument_list|)
expr_stmt|;
block|}
DECL|method|setSourceAlias
specifier|public
name|RolloverRequestBuilder
name|setSourceAlias
parameter_list|(
name|String
name|sourceAlias
parameter_list|)
block|{
name|this
operator|.
name|request
operator|.
name|setSourceAlias
argument_list|(
name|sourceAlias
argument_list|)
expr_stmt|;
return|return
name|this
return|;
block|}
DECL|method|addMaxIndexAgeCondition
specifier|public
name|RolloverRequestBuilder
name|addMaxIndexAgeCondition
parameter_list|(
name|TimeValue
name|age
parameter_list|)
block|{
name|this
operator|.
name|request
operator|.
name|addMaxIndexAgeCondition
argument_list|(
name|age
argument_list|)
expr_stmt|;
return|return
name|this
return|;
block|}
DECL|method|addMaxIndexDocsCondition
specifier|public
name|RolloverRequestBuilder
name|addMaxIndexDocsCondition
parameter_list|(
name|long
name|docs
parameter_list|)
block|{
name|this
operator|.
name|request
operator|.
name|addMaxIndexDocsCondition
argument_list|(
name|docs
argument_list|)
expr_stmt|;
return|return
name|this
return|;
block|}
DECL|method|simulate
specifier|public
name|RolloverRequestBuilder
name|simulate
parameter_list|(
name|boolean
name|simulate
parameter_list|)
block|{
name|this
operator|.
name|request
operator|.
name|simulate
argument_list|(
name|simulate
argument_list|)
expr_stmt|;
return|return
name|this
return|;
block|}
DECL|method|settings
specifier|public
name|RolloverRequestBuilder
name|settings
parameter_list|(
name|Settings
name|settings
parameter_list|)
block|{
name|this
operator|.
name|request
operator|.
name|getCreateIndexRequest
argument_list|()
operator|.
name|settings
argument_list|(
name|settings
argument_list|)
expr_stmt|;
return|return
name|this
return|;
block|}
DECL|method|alias
specifier|public
name|RolloverRequestBuilder
name|alias
parameter_list|(
name|Alias
name|alias
parameter_list|)
block|{
name|this
operator|.
name|request
operator|.
name|getCreateIndexRequest
argument_list|()
operator|.
name|alias
argument_list|(
name|alias
argument_list|)
expr_stmt|;
return|return
name|this
return|;
block|}
DECL|method|mapping
specifier|public
name|RolloverRequestBuilder
name|mapping
parameter_list|(
name|String
name|type
parameter_list|,
name|String
name|source
parameter_list|)
block|{
name|this
operator|.
name|request
operator|.
name|getCreateIndexRequest
argument_list|()
operator|.
name|mapping
argument_list|(
name|type
argument_list|,
name|source
argument_list|)
expr_stmt|;
return|return
name|this
return|;
block|}
block|}
end_class

end_unit

